name: Simon Barrett
description: Blogging about stuff since the other day
meta_description: "Simon Barrett, blogging about stuff since the other day"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'https://simonbarrett.dev'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Simon Barrett'
bio:            'programmer, cook, sometime teacher, enthusiastic banger of drums and not a <a href="https://en.m.wikipedia.org/wiki/Simon_Barrett_(filmmaker)">screenplay writer</a>'
