name: Simon Barrett
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'https://simonbarrett.dev'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Simon Barrett'
bio:            'programmer, sometime teacher, enthusiastic banger of drums and not a screenplay writer'
