name: Simon Barrett
description: Blogging about stuff since just the other day
meta_description: "Simon Barrett, blogging about stuff since just the other day"

twitter: simonbarrett

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: 'https://simonbarrett.dev'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]
permalink: /:categories/:year/:month/:day/:title

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-timeago

# Details for the RSS feed generator
subscribe:      false
url:            'blog url'
author:         'Simon Barrett'
bio:            'programmer, cook, sometime teacher, enthusiastic banger of drums and not a <a href="https://en.m.wikipedia.org/wiki/Simon_Barrett_(filmmaker)">screenplay writer</a>'
